# Generated by Django 6.0.6 on 2026-06-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_subscription_active',
            field=models.BooleanField(default=True),
        ),
    ]
