# Generated by Django 6.0.6 on 2026-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_customers',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_leads',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_users',
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
